### ISSUE TITLE
Instrucciones y documentación en inglés

### ISSUE THREAD

**Issue by ivancevich** [FAAREIA/ALFA#1]
Fede, ¿cómo estás?
Calculo que este repo es más que nada para tu uso personal, pero te recomiendo que las instrucciones y documentación estén también en inglés para que más desarrolladores puedan utilizarlo y sacarle el jugo.
Un abrazo!

**Comment by FAAREIA** [comment]
Hola Juan, gracias por abrir un issue. Entiendo lo que decis y me parece válido.
Dejo abierto el issue.
Abrazo!

**Comment by FAAREIA** [comment]
Hecho ;)
Abrazo bestia
